# Generated by Django 4.2 on 2023-08-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoikone', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='playground',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='園庭'),
        ),
    ]
