# Generated by Django 4.2 on 2023-08-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoikone', '0005_nursery_playground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='future',
            field=models.TextField(null=True, verbose_name='子どもと接するときに何を大事にしているか'),
        ),
    ]
