# Generated by Django 4.2 on 2023-08-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoikone', '0006_alter_nursery_future'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='feature',
            field=models.TextField(max_length=40, null=True, verbose_name='特色'),
        ),
    ]
