# Generated by Django 4.2 on 2023-08-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoikone', '0007_alter_nursery_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='feature',
            field=models.TextField(max_length=80, null=True, verbose_name='特色'),
        ),
    ]
