# Generated by Django 4.2 on 2023-08-11 06:44

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoikone', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'このユーザー名は使われています。別のユーザー名を入力して下さい。'}, help_text='必須項目です。半角英数字と@,.,+,-が使用できます。文字数は15文字以下までです。', max_length=15, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
