# Generated by Django 4.2 on 2023-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoikone', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_change',
            field=models.BooleanField(default=False),
        ),
    ]
