# Generated by Django 4.2 on 2023-08-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoikone', '0011_customuser_email_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_change_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
